# Generated by Django 4.2 on 2023-04-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_article_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profile'),
        ),
    ]
